# Generated by Django 5.0.7 on 2024-07-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('detailed_description', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('recommendation_count', models.IntegerField()),
            ],
        ),
    ]
